version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:18
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Check tests
          command: npm test

  build:
    docker:
      - image: circleci/node:18
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Construct Docker image
          command: docker build -t to-do-app .

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - build
