version: 2.1

jobs:
  test:
    docker:
      - image: docker:20.10.7-dind
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Debug Environment Variables
          command:  |
            echo "DOCKERHUB_USERNAME=$DOCKERHUB_USERNAME"
            if [ -z "$DOCKERHUB_PASSWORD" ]; then echo "DOCKERHUB_PASSWORD is NOT set"; else echo "DOCKERHUB_PASSWORD is set"; fi
      - run:
          name: Install Node.js
          command: apk add --no-cache nodejs npm
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Install SQLite
          command: apk add --no-cache sqlite
      - run:
          name: Run Tests
          command: npm test

  build:
    docker:
      - image: docker:20.10.7-dind
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Node.js
          command: apk add --no-cache nodejs npm
      - run:
          name: Build Docker Image
          command: docker build -t frank5005/to-do-app:latest .

  publish:
    docker:
      - image: docker:20.10.7-dind
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Node.js
          command: apk add --no-cache nodejs npm
      - run:
          name: Login to DockerHub
          command: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Push Docker Image
          command: |
            docker tag frank5005/to-do-app:latest frank5005/to-do-app:$CIRCLE_SHA1
            docker push frank5005/to-do-app:$CIRCLE_SHA1
            docker push frank5005/to-do-app:latest

workflows:
  version: 2
  build:
    jobs:
      - test
      - build
      - publish:
          requires:
            - build
