version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:18
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Install SQLite
          command: apt-get update && apt-get install -y sqlite3

  build:
    docker:
      - image: circleci/node:18
    steps:
      - checkout
      - run:
          name: Build Docker Image
          command: docker build -t frank5005/to-do-app:latest .

  publish:
    docker:
      - image: circleci/node:18
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Login to DockerHub
          command: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Push Docker Image
          command: docker push frank5005/todo-app:latest
            #docker tag todo-app $DOCKERHUB_USERNAME/todo-app:latest
            #docker push $DOCKERHUB_USERNAME/todo-app:latest

workflows:
  version: 2
  build:
    jobs:
      #- test
      - build
      - publish:
          requires:
            - build
